### ISSUE TITLE
Agregar propiedad value="{{old(name)}}"

### ISSUE THREAD

**Issue by cesar12p** [cesar12p/Recetario#18]
Si se edita una receta y algún campo no es  valido, al guardar pierdes todos tus nuevos cambios porque los datos los toma de array

**Comment by Francisco8NGY** [comment]
We esta cabron eso, por que ya estas usando el value para poner lo que tienes en db,  titnes alguna idea de como hacer eso?

**Comment by Francisco8NGY** [comment]
Necesitaria meterle un if

**Comment by Francisco8NGY** [comment]
ya quedo
